# Generated by Django 4.1 on 2022-08-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price_unit",
            field=models.CharField(default="da / pieces", max_length=20),
        ),
    ]
