# Generated by Django 4.1 on 2022-08-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product_price_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(null=True, upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_unit",
            field=models.CharField(default="da/pieces", max_length=20),
        ),
    ]
