# Generated by Django 4.1 on 2022-08-27 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="sub_product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField()),
                ("price_unit", models.CharField(default="da/pieces", max_length=20)),
                (
                    "description",
                    models.CharField(blank=True, max_length=800, null=True),
                ),
                (
                    "prod",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.product",
                    ),
                ),
            ],
        ),
    ]
