# Generated by Django 4.1 on 2022-08-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_sub_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="modelmadenew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("space", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=800, null=True)),
            ],
        ),
    ]
