# Generated by Django 4.1 on 2022-08-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_modelmadenew"),
    ]

    operations = [
        migrations.DeleteModel(name="modelmadenew",),
        migrations.AddField(
            model_name="sub_product",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
