# Generated by Django 4.1 on 2022-08-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_delete_modelmadenew_sub_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="options_dispo",
            field=models.BooleanField(default=False),
        ),
    ]
