# Generated by Django 4.1 on 2022-08-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_product_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="product_type",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
