# Generated by Django 4.1 on 2022-08-29 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_product_type_image"),
    ]

    operations = [
        migrations.RenameModel(old_name="product", new_name="products",),
    ]
