# Generated by Django 4.1 on 2022-08-29 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_rename_product_products"),
    ]

    operations = [
        migrations.RenameModel(old_name="sub_product", new_name="options_product",),
        migrations.RenameField(
            model_name="options_product", old_name="prod", new_name="product",
        ),
    ]
