# Generated by Django 4.1 on 2022-09-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_rename_sub_product_options_product_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adresse", models.CharField(max_length=100, null=True)),
                (
                    "numero",
                    models.CharField(
                        default="+213 xxxxxxxxx", max_length=15, null=True
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        default="xxxxxxx@gmail.com", max_length=100, null=True
                    ),
                ),
                (
                    "time",
                    models.CharField(
                        default="Weekday : 8h00 - 17h00", max_length=100, null=True
                    ),
                ),
            ],
        ),
    ]
