# Generated by Django 4.1 on 2022-09-01 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_contact"),
    ]

    operations = [
        migrations.RenameModel(old_name="contact", new_name="contacts",),
    ]
