# Generated by Django 4.1 on 2022-09-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0016_alter_options_product_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="brand",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="price_unit",
            field=models.CharField(default="da/pieces", max_length=20),
        ),
    ]
