# Generated by Django 4.1 on 2022-09-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0017_alter_products_brand_alter_products_price_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="brand",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
